import httpx
from changeguard_ai.core.config import settings
from changeguard_ai.models import RiskReport


GITHUB_API_BASE = "https://api.github.com"


def get_headers() -> dict:
    return {
        "Authorization": f"Bearer {settings.github_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


async def fetch_pr_files(repo: str, pr_number: int) -> list[str]:
    if not settings.github_token:
        return []

    url = f"{GITHUB_API_BASE}/repos/{repo}/pulls/{pr_number}/files"

    async with httpx.AsyncClient() as client:
        response = await client.get(url, headers=get_headers())

        if response.status_code != 200:
            return []

        files_data = response.json()
        return [f["filename"] for f in files_data]


def format_risk_report(report: RiskReport) -> str:
    level_emoji = {
        "low": "green_circle",
        "medium": "yellow_circle",
        "high": "orange_circle",
        "critical": "red_circle",
    }

    emoji = level_emoji.get(report.risk_level.value, "white_circle")
    human_review = "YES — senior review required" if report.requires_human_review else "NO"

    factors = "\n".join(f"- {factor}" for factor in report.top_risk_factors)

    return f"""## ChangeGuard AI — Deployment Risk Report

:{emoji}: **Risk Score: {report.risk_score}/100 — {report.risk_level.value.upper()}**

| Field | Value |
|---|---|
| Recommended Rollout | {report.recommended_rollout} |
| Human Review Required | {human_review} |

### Top Risk Factors
{factors}

### Summary
{report.summary}

---
*Generated by ChangeGuard AI — powered by Anthropic Claude*
"""


async def post_pr_comment(repo: str, pr_number: int, report: RiskReport) -> bool:
    if not settings.github_token:
        return False

    url = f"{GITHUB_API_BASE}/repos/{repo}/issues/{pr_number}/comments"
    comment_body = format_risk_report(report)

    async with httpx.AsyncClient() as client:
        response = await client.post(
            url,
            headers=get_headers(),
            json={"body": comment_body},
        )

        return response.status_code == 201